---
layout:  post
title: "Making Beech-Leaf Tea"
comments:  true
published:  true
author: "Zach Burchill"
date: 2020-05-14 01:00:00
permalink: /beech_tea/
categories: [nature,trees,tea,DIY,foraging,'for fun',beech,leaves,leaf]
output:
  html_document:
    mathjax:  default
    fig_caption:  true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, autocaption=TRUE,
  warning = FALSE, message = FALSE,  
  comment = "",
  dpi = 200
  )

library(tidyverse)
library(lubridate)
library(ggrepel)

ylabel <- "average rating"
xlabel <- "includes a question mark?"
```

I grew up in Indiana, and although I was a Boy Scout, and the occasional begrudging hiker, I would have never said I was an "outdoors" person.  But as I've gone through life, I've begun to suspect that this was a product of circumstances more than disposition.  I've fallen in love with hiking and camping in the American Southwest, and I think the reason why I never got excited about it growing up is that hiking in Indiana is *boring*.  

I don't know how I became aware of foraging (as a modern, hipster concept), but I do know that it's gotten me to pay much more attention to nature around me. Like hiking, I think that going outside would have been much more appealing to me as a child if somebody had told me how much of the outside you can just *eat*.

<!--more-->

This is one of my rare non-tech-related posts.  Mostly, I'm writing this so that I can remember what I did next year, but I think some of you might be interested in it as well.

## Hitting the beech

I love trees. Trees are so fucking great.  Like, damn, they are amazing.  Food, shelter, beauty, food, shade, biodiversity, food, *everything*. Some trees are particularly great. Beech trees, for example.

You can eat beech nuts (be careful with that though), the inner bark, and the young spring leaves.  You can also infuse alcohol with beech leaves, making a traditional drink called [beech leaf noyau](http://frontierbushcraft.com/2018/07/19/beech-leaf-noyau/). Of course, my desire for alcohol drove me to learn about how great beech trees are.  

Since I learned too late about this concoction last year, I've been waiting a whole year to make some of my own. I went out and collected my own this year, infusing two types with New Amsterdam gin. It turns out I had collected a few too many leaves, however, and after reading this [incredibly scant post about using beech leaves for tea](https://www.eatweeds.co.uk/beech-leaf-tea-recipe), I decided to try and make some of my own, following my own recipe.

Since I didn't actually *have* a recipe, I decided to loosely imitate what people did to actual tea leaves, given half an hour of research on the subject.

## Beech leaf tea recipe:

### Step 1: Get your leaves

Go out and collect a lot of young beech leaves. They should be soft, sticky, and very thin and paper-like. Test them out by chewing on one for a little bit. You should be hit with a citrusy *zing* after a few chews.  If they taste bad, avoid them if you can.  If you they're all you have, make this tea anyway and tell me how it turns out. I'm not even sure if you *need* young leaves for this recipe, anyway.  

I think leaves with at least a hint of red coloring in them will make your tea look very nice visually, so props if you can get those.

### Step 2: Detassling and wilting

After having collected all your leaves and returned home, start sorting them out, removing the husks and silky tassel-y bits, and spreading the leaves out on parchment paper or something to that effect (I used an Amazon silicon baking pad thing).  

The goal of this stage is to very, very gently dry the leaves out a little, and let them sit out for a few hours.  Maybe blow a little hot air over them if you can.

*Actual* tea leaves are said to "wilt" or "ferment" in this stage, and who knows, something like that might happen for these beech leaves as well.  Might as well play it safe, but if you have a lot of leaves, you can experiment and see if this is necessary.  Try throwing some in the oven immediately, try letting some sit for as long as you can.

### Step 3: Wilt harder

After letting the leaves sit out for a few hours, pre-heat the oven to the lowest setting you have. Spread out the leaves on a non-stick tray and put them in.

Now, this is a very touch-and-go stage.  I absolutely burned leaves at 200°F after baking them for around 15 minutes, so you want to be careful, maybe turning the oven off and on, checking on them very frequently, whatever.

You will want them to not be burnt or browned, but to loose a little more of their water.  You'll know they're ready when you can roll a leaf into a little ball or cigar shape with your fingers it stays like that.

### Step 4: Rollin', rollin', rollin'

When I was trying to make this tea, I was on an oolong tea kick, so I decided to try rolling the leaves up like little oolong balls. When you're doing this, the leaves should be very easy to roll, and you should see that they compress a lot in the process.

I tried two different techniques: rolling leaves into tiny balls and tiny cigar shapes, both between my palms (using the same methods kids form snakes and balls out of Play-Doh).  For small leaves, I rolled them together, but for some of the big leaves, I rolled them into balls by themselves.  You really want to emulate oolong here.
 
I did this process so that when we put them in the oven for longer, they won't burn as quickly, having much smaller surface area relative to volume, and being much denser.

### Step 5: Bake 'n' bake

For this final step, put them back into the oven at that very low temperature, and continue to check on them. You want them to get as bone-dry as you can, since having a very low moisture content is vital for long-term storage.    

Try not to burn them, but they should feel like desiccated husks when you're done. If you have some method of blowing hot air over them, do that too for sure, but let them get at least a *little* roast-y.

### Step 6: Enjoy?

I only made one good batch of the stuff, so I don't really know what the proper amount of leaves is or how long you should steep it for. I just threw all the leaves that I had (I'd say about 2.5 times the amount of tea you'd normally use for oolong) into an eight ounce cup and poured boiling water on top of that. I know I let it steep for at least five minutes, but I probably steeped it for upwards of ten or fifteen, since I was dead set on getting this batch to have flavor.

If it worked right, you should be able to tell instantly by its very strong, very pleasant smell, which is present in the steeped tea but not really in the dry form.  It was very hard for me to place, but smelled a little like licorice and hazelnut, with hints of a wet forest floor in the autumn. The smell is definitely this tea's biggest strength---it's much more pungent than any but the most overwrought herbal tea that I've tried (in a very good way), and it has an incredibly light flavor.

I wanted to extract the citrus-y taste of the leaves when chewed, and it's there---*kinda if you imagine hard*.  The tea has a very faint, light, bright flavor.  I think it would be an excellent complement to an herbal mix that needs a cozy "fall" smell, but already has the flavor part covered.

Another thing that surprised me about this tea was its color. I wish I had taken pictures, but it was an incredible shade of *pink*. Like, *bubblegum* pink.  I had collected leaves from the wonderful [*fagus sylvatica purpurea tricolor*](https://www.gardenia.net/plant/fagus-sylvatica-purpurea-tricolor) specimen [in Highland park](https://books.google.com/books?id=a72sBgAAQBAJ&pg=PT29&lpg=PT29#v=onepage&q&f=false), along with a few other red-tinted beeches nearby (behind the Lamberton conservatory, as you can see [here](https://static1.squarespace.com/static/56ce567d4d088e72561bf781/t/5a669412652dea8822404458/1516672034159/Botanical+Map.jpg)), so I think that might have had something to do with it.[^1]

If anybody else makes this, please contact me [on Twitter](https://twitter.com/zachburchill) and tell me how it worked out and what you did! 

<hr />
<br />


### Footnotes:

[^1]: Also, there is a *crazy* beech tree just a little to the left of the main entrance to Mount Hope cemetary. Not only is it the most massive beech tree I've ever seen, but it had blood-red leaves and white bark, making it look just like the trees in the [godswood in *Game of Thrones*](https://www.ign.com/wikis/game-of-thrones/Godswood). I harvested some for a batch of beech leaf noyau, and the gin's already red as heck.
